## 03-09-22

In [1]:
l1 = [1,2,3,4,5]
l2 = []
for x in l1:
    l2.extend([x*2.5])
print(l2)

[2.5, 5.0, 7.5, 10.0, 12.5]


In [2]:
l = [1,2,3,4]
for x in l:
    print(x, "*", 2.5, "=", x*2.5)

1 * 2.5 = 2.5
2 * 2.5 = 5.0
3 * 2.5 = 7.5
4 * 2.5 = 10.0


In [3]:
new = [x*2.5 for x in l]
print(new, type(new))

[2.5, 5.0, 7.5, 10.0] <class 'list'>


In [4]:
import numpy as np
np_1 = np.array([1,2,3,4,5])

In [5]:
type(np_1)

numpy.ndarray

In [6]:
print(np_1*2.5)
type(np_1)

[ 2.5  5.   7.5 10.  12.5]


numpy.ndarray

In [7]:
np_2 = np.array([1,2,3,4,5,6,7,8,9,10])
np_2**2-2


array([-1,  2,  7, 14, 23, 34, 47, 62, 79, 98], dtype=int32)

In [8]:
type(np_2)

numpy.ndarray

In [9]:
np_3 = np.array([1, "abc", "True"])
np_3

array(['1', 'abc', 'True'], dtype='<U11')

In [10]:
for x in np_3:
    print(type(x))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [11]:
list1 = np.array([1,2,3])
list2 = np.array([4,5,6])

list1 + list2

array([5, 7, 9])

In [12]:
# create an array from numbers 1-10. Replace all odd numbers in the given array with -1

l1 = np.array([1,2,3,4,5,6,7,8,9,10])

l1[l1 % 2 != 0] = -1
print(l1)

# replace all even numbers with +1
l1[l1 % 2 == 0] = +1
print(l1)

[-1  2 -1  4 -1  6 -1  8 -1 10]
[-1  1 -1  1 -1  1 -1  1 -1  1]


In [13]:
# wap to check if an element in array is 0 or not
# if zero, keep as is, or if its not 0, replace it by 1
abc = np.array([1,3,6,0,8])
abc[abc == 0] = 0
abc[abc != 0] = 1
abc

array([1, 1, 1, 0, 1])

In [14]:
# you cannot assign str value to int eements
abc = np.array([1,-4,3,-10,-15,6,20,8,9,10])
abc[abc-abc == 0] = "pos"
abc[abc+(-abc) == 0] = "neg"

ValueError: invalid literal for int() with base 10: 'pos'

In [ ]:
np.arange(5)

In [ ]:
arr = np.arange(10)
print(arr)
arr.reshape(2,-1)

In [ ]:
arr2 = np.arange(8)
arr3 = arr2.reshape(2,4)
arr4 = arr2.reshape(4,2)
print(arr3)
print(arr4)

In [ ]:
random_array = np.random.randint(30, 42, size = 12)
len(random_array)

In [69]:
# create an array pf number 1-100 and convert it into a 3d array
a = np.arange(30).reshape(2,3,5)
print(a)
print(a.ndim)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
3


## 04-09-22

In [15]:
# to make an array with digits within a range 

np.arange(start=10, stop=20, step=1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [17]:
np.arange(start=10, stop=20, step=2)

array([10, 12, 14, 16, 18])

In [18]:
np.arange(10,20,1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [19]:
np.arange(12,25,3)

array([12, 15, 18, 21, 24])

In [24]:
#define a 2d array with 10 members and reshape in 2,5 and 5,2 array
c = np.arange(2,12,1)
p = c.reshape(2,5)
d = c.reshape(5,2)
print(p)
print(d)

[[ 2  3  4  5  6]
 [ 7  8  9 10 11]]
[[ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [71]:
#making a matrix
a = np.array([[1,1,1],
              [2,2,2],
              [3,3,3]])
a.ndim

2

In [35]:
import time
import sys

In [37]:
#list vs numpy wrt size and convienence
SIZE = 1000

#create 2 lists
L1 = range(SIZE)
L2 = range(SIZE)

#make 2 arrays
A1 = np.arange(SIZE)
A2 = np.arange(SIZE)

In [44]:
type(L1)

type(L2)

type(A1)

type(A2)



range

range

numpy.ndarray

numpy.ndarray

In [52]:
start = time.time()
result = [(x+y) for x,y in zip(L1,L2)] #Adding 2 lists
#calculate time taken for list
time_by_list = (time.time() - start)*1000   #for miliseconds
time_by_list

0.9999275207519531

In [53]:
result  #result of adding 2 lists

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

In [65]:
#for numpy arrays
start = time.time()
result = A1 + A2
time_by_arr = (time.time() - start)*1000
time_by_arr

1.0006427764892578

In [60]:
result

array([   0,    2,    4,    6,    8,   10,   12,   14,   16,   18,   20,
         22,   24,   26,   28,   30,   32,   34,   36,   38,   40,   42,
         44,   46,   48,   50,   52,   54,   56,   58,   60,   62,   64,
         66,   68,   70,   72,   74,   76,   78,   80,   82,   84,   86,
         88,   90,   92,   94,   96,   98,  100,  102,  104,  106,  108,
        110,  112,  114,  116,  118,  120,  122,  124,  126,  128,  130,
        132,  134,  136,  138,  140,  142,  144,  146,  148,  150,  152,
        154,  156,  158,  160,  162,  164,  166,  168,  170,  172,  174,
        176,  178,  180,  182,  184,  186,  188,  190,  192,  194,  196,
        198,  200,  202,  204,  206,  208,  210,  212,  214,  216,  218,
        220,  222,  224,  226,  228,  230,  232,  234,  236,  238,  240,
        242,  244,  246,  248,  250,  252,  254,  256,  258,  260,  262,
        264,  266,  268,  270,  272,  274,  276,  278,  280,  282,  284,
        286,  288,  290,  292,  294,  296,  298,  3

In [72]:
a = np.array([(1,2,3,4,5,6,7),(8,9,10,11,12,13,14)])
a[:,2]

array([ 3, 10])

In [73]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [83]:
a[1,4] = 20
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 20, 13, 14]])

In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"